# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'AskServerPort.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_AskServerPort(object):
    def setupUi(self, AskServerPort):
        AskServerPort.setObjectName("AskServerPort")
        AskServerPort.resize(400, 300)
        self.verticalLayout = QtWidgets.QVBoxLayout(AskServerPort)
        self.verticalLayout.setObjectName("verticalLayout")
        self.widget = QtWidgets.QWidget(AskServerPort)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.widget.setFont(font)
        self.widget.setObjectName("widget")
        self.gridLayout = QtWidgets.QGridLayout(self.widget)
        self.gridLayout.setObjectName("gridLayout")
        self.spinBox = QtWidgets.QSpinBox(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.spinBox.sizePolicy().hasHeightForWidth())
        self.spinBox.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.spinBox.setFont(font)
        self.spinBox.setMaximum(65535)
        self.spinBox.setObjectName("spinBox")
        self.gridLayout.addWidget(self.spinBox, 4, 0, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem, 5, 0, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem1, 3, 0, 1, 1)
        self.label = QtWidgets.QLabel(self.widget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 1, 0, 1, 1)
        self.messsage_box = QtWidgets.QLabel(self.widget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.messsage_box.setFont(font)
        self.messsage_box.setObjectName("messsage_box")
        self.gridLayout.addWidget(self.messsage_box, 2, 0, 1, 1)
        self.verticalLayout.addWidget(self.widget)
        self.buttonBox = QtWidgets.QDialogButtonBox(AskServerPort)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.verticalLayout.addWidget(self.buttonBox)

        self.retranslateUi(AskServerPort)
        self.buttonBox.accepted.connect(AskServerPort.accept) # type: ignore
        self.buttonBox.rejected.connect(AskServerPort.reject) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(AskServerPort)

    def retranslateUi(self, AskServerPort):
        _translate = QtCore.QCoreApplication.translate
        AskServerPort.setWindowTitle(_translate("AskServerPort", "Dialog"))
        self.label.setText(_translate("AskServerPort", "选择套接字端口（0表示关闭服务器）"))
        self.messsage_box.setText(_translate("AskServerPort", "TextLabel"))
